### ISSUE TITLE
[Crash]: Crash during initialization

### ISSUE THREAD

**Issue by ghost** [dimadencep/RemoveReloadingScreen#1]
### Mod Loader

Forge 36.2.39

### Minecraft Version

1.16.5

### Mod Version

1.3.0.12

### Notes

Note: Conflict with Resource Pack Overrides. I am reporting this problem to the developers of both mods.

1. Run Minecraft.
2. Exit with code 1.

### latest.log

[latest.txt](https://github.com/dimadencep/RemoveReloadingScreen/files/11009885/latest.txt)

**Comment by Fuzss** [comment]
@dimadencep Please don’t use `@Overwrite`, use `@Inject` at `HEAD` instead, then cancel the callback for `!MainMod.config.resetResources`.
