### ISSUE TITLE
Resource Reload Failed

### ISSUE THREAD

**Issue by bbbdbdtp** [dimadencep/RemoveReloadingScreen#101]
### Minecraft version.

Fabric 1.21

### Remove Reloading Screen version.

Beta v5.0.4

### What happened?

When I'm trying to connect to server(Server on 1.20.1, I'm playing on 1.21). I can't connect.
I record it in [Youtube Video](https://youtu.be/ZPr97t1xHDU). 

I have other mods, exclude RRLS, but When i disable RRLS in MultiMC launcher, i haven't this problem and I can connect and play. So, I believe that is a 100% problem of RRLS.

P.S. Sorry for my English, I'm only A2-B1 maybe, it can be awful.

### Relevant log.

[latest.log](https://github.com/user-attachments/files/16337261/latest.log)
[latest.log](https://github.com/user-attachments/files/16337267/latest.log)

**Comment by bbbdbdtp** [comment]
Только что прочитал что создатель мода из России). Крч на русском напишу чтоб ты не читал мой ужасный английский.

Я юзаю ViaFabric чтоб подключиться к серверу который стоит на ядре 1.20.1, а я играю с 1.21. И тут у меня закрывается сервер и перебрасывает на меню мультиплеера, из-за RRLS мода. причём когда я отключаю RRLS мод, у меня запускается сервер, появляется ошибка **Resource Reload Failed** Но я всё ещё нахожусь на сервере, и на ошибку похуй, она пропадает через 3 секунды а на сервере я могу играть нормально.

Как я уже написал выше, проблема точно в RRLS, потому что я отключил его, и без него всё работает, когда я включаю RRLS, то сервер начинает закрываться после ошибки **Resource Reload Failed**.

Если нужны дополнительные данные, можешь написать в тг @stokmenn

**Comment by dima-dencep** [comment]
The error in the server resourcepack, you can tweak the rrls config to fix this

**Comment by dima-dencep** [comment]
![image](https://github.com/user-attachments/assets/eb0d4cfc-4921-4bdf-bb47-8e09c615090b)
