### ISSUE TITLE
Game crashes with my Vanilla+ modpack

### ISSUE THREAD

**Issue by ghost** [dimadencep/RemoveReloadingScreen#103]
### Minecraft version.

1.21

### Remove Reloading Screen version.

5.0.5+mc1.21-fabric

### What happened?

I started the game and it imediatly crashed

### Relevant logs

[2024-07-30-6.log.gz](https://github.com/user-attachments/files/16426496/2024-07-30-6.log.gz)

### Additional information

Here are the mods that I am using:

![Screenshot (22)](https://github.com/user-attachments/assets/48ec8a54-285c-41c5-9f8d-306916935a0d)
![Screenshot (23)](https://github.com/user-attachments/assets/b5d757e1-39ca-4d5f-9866-6ede1a305734)

**Comment by dima-dencep** [comment]
Are you sure that removing rrls solves your problem?

**Comment by ghost** [comment]
yes 100%. I removed every mod 1 by 1 but only removing rrls soved the problem

**Comment by dima-dencep** [comment]
What happens if you remove the skin shuffle?

**Comment by ghost** [comment]
that works thanks

**Comment by ghost** [comment]
but is there a chance that they work togeter?

**Comment by dima-dencep** [comment]
I already have a hack for the skin shuffle but apparently it's not enough, if there are details I'll fix it, but for now it's not a rrls problem

**Comment by ghost** [comment]
okay thx

**Comment by dima-dencep** [comment]
I know changing the skin via essential works, you can try that, or create a issue in skin shuffle

**Comment by dima-dencep** [comment]
I realized that badoptimizations were to blame
