### ISSUE TITLE
Crash with Hey Wiki and Zoomify

### ISSUE THREAD

**Issue by Dianliang233** [dimadencep/RemoveReloadingScreen#108]
### Minecraft version.

1.21

### Remove Reloading Screen version.

5.0.0+mc1.21-fabric

### What happened?

1. Install [Hey Wiki](https://github.com/mc-wiki/minecraft-mod-heywiki), [Zoomify](https://modrinth.com/mod/zoomify), RRLS & dependency
2. Run game
3. Game crashes

### Relevant logs

Log: [pastebin.com/sExLhZVi](https://pastebin.com/sExLhZVi) password: heywiki
Crash log: [files.catbox.moe/bnozsp.txt](https://files.catbox.moe/bnozsp.txt) no password

### Additional information

This was originally reported as https://github.com/mc-wiki/minecraft-mod-heywiki/issues/58. I  have since narrowed it down to three mods: RRLS, Hey Wiki and Zoomify.

Hey Wiki requires [some resources](https://github.com/mc-wiki/minecraft-mod-heywiki/blob/master/common/src/main/java/wiki/minecraft/heywiki/resource/WikiFamilyManager.java) to be loaded and it will [manipulate the TitleScreen](https://github.com/mc-wiki/minecraft-mod-heywiki/blob/master/fabric/src/main/java/wiki/minecraft/heywiki/fabric/mixin/TitleScreenMixin.java)

**Comment by dima-dencep** [comment]
Update rrls

**Comment by Dianliang233** [comment]
@dima-dencep I can also reproduce this in the latest version (5.0.7)

**Comment by dima-dencep** [comment]
I can't fix it in rrls, since heywiki does mixin, the fix has to be done there (which I see has been done)

I just woke up, I have no idea how to fix this in rrls, maybe your ideas?

**Comment by dima-dencep** [comment]
To some extent, this is a duplicate of #87

**Comment by Dianliang233** [comment]
I'm a bit curious – is it intended for TitleScreen to be shown even if not all resources are loaded?

**Comment by Dianliang233** [comment]
The fix seems to be simple enough — just need to get the part where the resource reloader is depended into the closure so that it is only executed when needed. I'm still curious why it requires RRLS and Zoomify to be installed in order for this issue to appear. Especially the Zoomify part, because I can't figure out how the heck Zoomify would play a role here.

**Comment by dima-dencep** [comment]
> is it intended for TitleScreen to be shown even if not all resources are loaded?

yeah, it's for all screens
