### ISSUE TITLE
Iris Incompatibility

### ISSUE THREAD

**Issue by Oregano1963** [dimadencep/RemoveReloadingScreen#109]
### Minecraft version.

1.21.0

### Remove Reloading Screen version.

5.0.7

### What happened?

Crashes after changing resource packs. Adding or removing any will result in the bar stalling towards the end until the game crashes.

### Relevant logs

https://mclo.gs/lo0jABW

### Additional information

Crash doesn't happen without this mod enabled

**Comment by dima-dencep** [comment]
show `/home/********/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/Asphalt 1.21.0/.minecraft/hs_err_pid2842.log`

**Comment by Oregano1963** [comment]
[hs_err_pid2842.log](https://github.com/user-attachments/files/16700921/hs_err_pid2842.log)

**Comment by dima-dencep** [comment]
I don't know, everything points to radeonsi and that is your video card
Since I have an AMD video card, I will try to reproduce this with it.

**Comment by Oregano1963** [comment]
any updates?

**Comment by dima-dencep** [comment]
Well, I haven't been able to reproduce it yet

**Comment by Oregano1963** [comment]
I just tried again and it only happens when in a world. If you tried on the menu, that might be why you couldn't reproduce it.

**Comment by dima-dencep** [comment]
Can you share the modpack that this is happening on?

**Comment by Oregano1963** [comment]
I was playing on this MR pack https://modrinth.com/modpack/asphalt

**Comment by Oregano1963** [comment]
OK. This is an incompatibility with Iris. Download Iris and rrls, turn on shaders, and change resource packs while in a world. Should crash the game.

1.21.1. rrls 5.0.8, iris beta 8

**Comment by dima-dencep** [comment]
What shaders? Everything's fine on complementary (ultra profile)

**Comment by Oregano1963** [comment]
Might be an issue for my machine only but comp and miniature both cause crashes with rrls. The pack shouldn't matter

**Comment by Oregano1963** [comment]
Seems to be fixed on 1.21.3 but I'll have to test more

**Comment by dima-dencep** [comment]
works on 1.21.1

![2024-11-10_07 17 14](https://github.com/user-attachments/assets/27a35d04-3f20-4dbf-883e-f1d16414354c)
