### ISSUE TITLE
Starting MC with the mod completely screws up the main menu.

### ISSUE THREAD

**Issue by cobaltlol2** [dimadencep/RemoveReloadingScreen#110]
### Minecraft version.

1.21

### Remove Reloading Screen version.

5.0.7

### What happened?

![image](https://github.com/user-attachments/assets/c5d9f223-f7a7-4d90-b699-6a7f12627e7b)
I expected the mod to work as expected. (It fixes by itself after the loading screen disappears from the mod)

### Relevant log.

https://pastebin.com/8CN8uhe0

### Additional information.

https://modrinth.com/modpack/true-vanilla+/version/LRUBD1M8 (my modpack link)

**Comment by dima-dencep** [comment]
This is normal behavior if the screen corrects itself after the loading is complete

**Comment by iminlikewithyou** [comment]
> This is normal behavior if the screen corrects itself after the loading is complete

that's true - but i think it's not unexpected for there to still be a loading screen when no resources have even been initialized yet
there should be an option so that there's still a loading screen on the first start of the game, to avoid seeing this strange screen

**Comment by dima-dencep** [comment]
You can specify which overlays to hide and which not to hide in the rrls config

**Comment by dima-dencep** [comment]
@iminlikewithyou Please check if it's gone or not
