### ISSUE TITLE
Texture Glitching when launching Minecraft with some dark mode and font changing packs installed

### ISSUE THREAD

**Issue by TechySC23** [dimadencep/RemoveReloadingScreen#111]
### Minecraft version.

1.21.1

### Remove Reloading Screen version.

v5.0.7

### What happened?

So whenever loading minecraft with the mods and texture packs below it first shows the pink and black (Missing texture block, ik) on the buttons and Vertical Rectangles instead of text except the minecraft logo and the splash text (yellow one) then it becomes normal.

### Relevant log.

https://paste.gg/p/anonymous/0a0578146a3246daa80189f98005f75d

### Additional information.

Interference possible mod: Kennytv's forcecloseworldloadingscreen
Resource pack with MOST DOUBT: Qrafty's Capitalized font and Default Dark Mode (https://modrinth.com/resourcepack/default-dark-mode)

**Comment by dima-dencep** [comment]
![2024-09-26_04 20 54](https://github.com/user-attachments/assets/667ab423-4a94-4745-82e4-70710685816a)
