### ISSUE TITLE
client side mod caused server crash -Rrls mod

### ISSUE THREAD

**Issue by xarsen1cx** [dimadencep/RemoveReloadingScreen#117]
### Minecraft version.

Version: 1.19.2

### Remove Reloading Screen version.

1.19.2-3.1.1

### What happened?

User downloaded your modpack version off our website.
and the server crash due to this being in the file as a client side mod.

### Relevant logs

https://paste.cybrancee.com/lihuquvakorucojeroma.properties

### Additional information

when user removed this Rrls from mods folder, server started up.

**Comment by dima-dencep** [comment]
That's right, the client mod causes a crash on the server because it's not designed for it
