### ISSUE TITLE
Toast as progress indicator

### ISSUE THREAD

**Issue by Madis0** [dimadencep/RemoveReloadingScreen#23]
I've been thinking of ways to make the loading state more obvious without being obtrusive. Full-screen splash may be too obtrusive even for a short period, yet implementing some kind of loading bar may be difficult to maintain and style (for different resource packs)

Now I've gotten a simple idea - how about using vanilla toast popups like the tutorial, recipes and narrator do? I think these can be used by mods without creating too many mixins, but I haven't checked yet. The most important thing is ensuring they stay visible throughout the loading process, however long it may be.

**Comment by dima-dencep** [comment]
Yes, when the next version of minecraft comes out, I will completely redo the patch for [SplashOverlay](https://github.com/dimadencep/RemoveReloadingScreen/blob/1.19.x/dev/common/src/main/java/com/github/dimadencep/mods/rrls/mixins/SplashOverlayMixin.java).

**Comment by dima-dencep** [comment]
https://github.com/dimadencep/RemoveReloadingScreen/releases/tag/1.19.4-2.0.0-dev

**Comment by Madis0** [comment]
That loading bar looks great! It is so intuitive that I would actually disable the text when using this (and I did, by blanking out the localization string).
