### ISSUE TITLE
Letters displayed as rectangles 

### ISSUE THREAD

**Issue by Madis0** [dimadencep/RemoveReloadingScreen#24]
With some mod/resource pack combination, the letters of the game font are displayed as rectangles for the first few seconds on game startup. Afterwards, the issue does not come back within the same game session, even if switching resource packs.

I haven't found the exact cause for this issue yet, but I thought I'd post it anyway in case you have an idea.

**Comment by dima-dencep** [comment]
Tell us more about these resourcespacks/mods

**Comment by Madis0** [comment]
I figured it out now. Seems like any combination of high-resolution resource packs will create the issue, presumably because they just load longer than "normal".

![2023-04-12_21 09 46](https://user-images.githubusercontent.com/8611110/231546526-f3af2605-07eb-4bd4-8978-e4c9ec242915.png)
![2023-04-12_21 08 55](https://user-images.githubusercontent.com/8611110/231546534-5d5c94c8-b4dc-4ce9-abd4-d29d3b5545d8.png)
![2023-04-12_21 08 20](https://user-images.githubusercontent.com/8611110/231546537-c89d6670-3b28-4b3f-b419-a9b18383d53e.png)

In the screenshots, these 3 were used with varying order:
* https://www.curseforge.com/minecraft/texture-packs/minecraft-hd-64x-fan-updated-by-mrdhobbs
* https://www.curseforge.com/minecraft/texture-packs/monsterley-hd
* https://www.curseforge.com/minecraft/texture-packs/faithful-64x

**Comment by dima-dencep** [comment]
Make sure you have the `Hide loading screen` option disabled in the mod settings

**Comment by Madis0** [comment]
Yup, that was the thing. 
I wanted to see what the option does so I enabled it at some point, but then I didn't draw the connection between the issue and the toggle :facepalm:
