### ISSUE TITLE
Mod gets stuck on attempting double-reload

### ISSUE THREAD

**Issue by Madis0** [dimadencep/RemoveReloadingScreen#25]
1. Add a server that requires resource packs, e.g. `cubecraft.net`, ensure it forces the installation on join
2. Join the server
3. Leave the server in the middle of the resource load

The mod shows a tooltip saying "resource reload has already started" and the "Reloading resources..." stays on screen.

**Comment by dima-dencep** [comment]
@Madis0 Please check if the textures reload correctly with this fix

https://github.com/dimadencep/RemoveReloadingScreen/releases/tag/1.19.4-2.0.0-dev

**Comment by Madis0** [comment]
No. The toast is gone, but the progress bar stays on screen in an almost-complete state.

**Comment by dima-dencep** [comment]
@Madis0 https://github.com/dimadencep/RemoveReloadingScreen/releases/tag/1.19.4-2.0.2-dev

**Comment by dima-dencep** [comment]
I tested this build, I did not freeze, in fact, I tested the previous build and there was nothing like that either

**Comment by Madis0** [comment]
You're right, in isolation the bug does not appear in neither of the versions you've linked. 

There seems to be some kind of mod conflict with [my modpack's](https://www.curseforge.com/minecraft/modpacks/fabulously-optimized/files) latest version, which makes it appear, but I haven't narrowed it down to the problematic mod yet. So... up to you whether you'd like to test and find the cause, or close the issue and I'll make another one once I've figured it out.

**Comment by dima-dencep** [comment]
This is due to the "Allow broken paths in resourcepacks" option in CITResewn and the "continuity:default" resourcepack being enabled.

**Comment by dima-dencep** [comment]
I don't know how to fix it yet. Why did you enable this option? (Author citresewn warns that there may be problems with this)

**Comment by Madis0** [comment]
> Why did you enable this option? (Author citresewn warns that there may be problems with this)

Mainly because Optifine has it enabled too and therefore many resource packs rely on this broken behavior.

**Comment by dima-dencep** [comment]
Do you know an example of such resourcepacks?

**Comment by dima-dencep** [comment]
@Madis0 https://modrinth.com/mod/rrls/version/1.20-3.0.0-fabric

**Comment by dima-dencep** [comment]
As soon as all bugs are fixed, I will backport to versions 1.19.4 - 1.18.2 (without 1.16.5, because this mod uses features added in java 17).

**Comment by Madis0** [comment]
3.0.0 works smoothly on Fabulously Optimized 5.0.0-alpha.1 :tada:
