### ISSUE TITLE
Progress bar isn't displayed when reloading text disabled

### ISSUE THREAD

**Issue by Felix14-v2** [dimadencep/RemoveReloadingScreen#26]
As the title says, when you disable reloading text, the reloading progress bar disappears when reloading.
![image](https://user-images.githubusercontent.com/75726196/234942531-2805db97-5791-4210-99cb-ec27e3cf8dfd.png)

* [x] Latest version (2.0.0 pre-release)

**Comment by dima-dencep** [comment]
This is not an bug, if you want to delete the text, just leave the field at the end blank

**Comment by Felix14-v2** [comment]
> This is not an bug, if you want to delete the text, just leave the field at the end blank

Oh, nice workaround :D
So this setting will be renamed? Iirc it was named "Show reload **text** in ..."

**Comment by dima-dencep** [comment]
https://github.com/dimadencep/RemoveReloadingScreen/releases/tag/1.19.4-2.0.1-dev
