### ISSUE TITLE
Problems in multiplayer servers

### ISSUE THREAD

**Issue by Catfl** [dimadencep/RemoveReloadingScreen#28]
### Minecraft version.

1.19.2

### Remove Reloading Screen version.

Rrls 1.5.0 Fabric 1.19.2

### What happened?

In multiplayer games, when the player tries to enter the login command, the keyboard will not work, but ESC working

### Relevant log.

[2023-06-07-3.log](https://github.com/dimadencep/RemoveReloadingScreen/files/11682359/2023-06-07-3.log)

**Comment by Catfl** [comment]
[2023-06-07-3.log](https://github.com/dimadencep/RemoveReloadingScreen/files/11682363/2023-06-07-3.log)
Supplementary send log

**Comment by dima-dencep** [comment]
Sorry, I played a very long time on 1.19.2 and I can say with certainty that such a problem with my mod does not.

**Comment by Felix14-v2** [comment]
> [2023-06-07-3.log](https://github.com/dimadencep/RemoveReloadingScreen/files/11682363/2023-06-07-3.log) Supplementary send log

Can you reproduce this issue without RRLS?

**Comment by Catfl** [comment]
Sorry, I didn’t see the error report clearly. In fact, ur mod is no problem. It‘s caused by a mod that opens the accelerated startup interface.

**Comment by Catfl** [comment]
sorry for the inconvenience
