### ISSUE TITLE
Incorrect handling of broken resources (overlay softlock)

### ISSUE THREAD

**Issue by DreenDex** [dimadencep/RemoveReloadingScreen#29]
### Minecraft version.

1.20

### Remove Reloading Screen version.

2.0.0-fabric

### What happened?

Softlock in overlay. No moving allowed (seems like client player don't tick) and screens don't show.

### Relevant log.

Reproduction steps:
1) Open the game and join in singleplayer world.
2) Load any broken resourcepack. (I attached one)
3) Observe how player's hand doesn't rotate with camera, you can't move and any screen is invisible. Everything is non-interactive.

Broken resourcepack primer for 1.20:
[somerandompack.zip](https://github.com/dimadencep/RemoveReloadingScreen/files/11691311/somerandompack.zip)

**Comment by dima-dencep** [comment]
In vanilla minecraft an error occurs when loading such a package, then the game resets the resources and loads them again, this mod disables this feature, it is easy to fix by enabling "Reset resources when failed load" in the configuration.

**Comment by dima-dencep** [comment]
Hmm, it still doesn't seem to work the way it's supposed to.

**Comment by dima-dencep** [comment]
@DreenDex

This should be fixed in V3, but if not, open this issue again.
https://modrinth.com/mod/rrls/version/1.20-3.0.0-fabric
