### ISSUE TITLE
Hides FancyMenu menus while reloading

### ISSUE THREAD

**Issue by HaXrDEV** [dimadencep/RemoveReloadingScreen#33]
### Minecraft version.

1.20.1

### Remove Reloading Screen version.

1.20-3.0.0-fabric

### What happened?

When reloading textures the FancyMenu title screen reverts to the vanilla one while it is occuring. 

In addition to this: When it finishes loading, the menu returns but with the vanilla buttons still visible.

![image](https://github.com/dimadencep/RemoveReloadingScreen/assets/20630404/6f3ed1d4-5f51-44dd-9635-8997c8bb5ddd)

### Relevant log.

N/A

**Comment by HaXrDEV** [comment]
Note that opening and closing a menu makes it go back to normal.

**Comment by dima-dencep** [comment]
Provide a log of the game, please

**Comment by dima-dencep** [comment]
Are you sure you didn't turn on the "Hide loading screen" option?

**Comment by HaXrDEV** [comment]
Sure thing, my bad: https://mclo.gs/hmx5iZF

**Comment by HaXrDEV** [comment]
> Are you sure you didn't turn on the "Hide loading screen" option?

Nope, have not touched the settings at all.

**Comment by dima-dencep** [comment]
Check this bug without my mod

**Comment by HaXrDEV** [comment]
> Check this bug without my mod

Do you mean the issue with the vanilla buttons sticking around after a reload? That issue doesn't occur without your mod installed.

Also, this is only something that comes up when reloading and then immediately going out to the title screen. IF you just stay and let it finish reloading before closing out, there is no problems.

**Comment by dima-dencep** [comment]
Try disabling/enabling the "Reinitializing the current screen after a reload" option.

**Comment by HaXrDEV** [comment]
> Try disabling/enabling the "Reinitializing the current screen after a reload" option.

It's the same exact behavior regardless of that setting being on or off.

**Comment by dima-dencep** [comment]
Unfortunately, this problem is partly on FancyMenu's side, but I will try to fix it as much as possible

**Comment by dima-dencep** [comment]
It seems to be more complicated than I thought, write to the author of FancyMenu about it, most likely the error is related to [MixinLoadingOverlay](https://github.com/Keksuccino/FancyMenu/blob/fabric-1.20.1/src/main/java/de/keksuccino/fancymenu/mixin/client/MixinLoadingOverlay.java)

**Comment by Keksuccino** [comment]
Hi, dev of FancyMenu here!

Yeah, that indeed seems like it's on FancyMenu's end and is related to how I handle (re)loading screens.
I am currently working on FancyMenu v3 and will try to make these two mods compatible, but no promises.

**Comment by Keksuccino** [comment]
Little update:

I was able to make RRLS and FM work together in FM v3.

I am checking if the `com.github.dimadencep.mods.rrls.Rrls` class exists and use `com.github.dimadencep.mods.rrls.accessor.SplashAccessor#isAttached()` to check if I need to fix the screen after it got initialized in the RRLS overlay.

**Comment by dima-dencep** [comment]
@Keksuccino 
Ideally, LoadingOverlay (SplashOverlay) should not be touched at all.

**Comment by Keksuccino** [comment]
@dima-dencep 
But..your mod overrides its whole render body.. Isn't that the exact opposite of "not touching it"?

And yeah well, there would be a permanent "bug" where the vanilla menu shows up instead of the customized one every time the loading screen is fading in/out (or while your invisible loading screen is active) when I'm not placing mixins in the overlay, so no, that's not possible, sorry.

Both mods work great together now (at least with FancyMenu v3, which is still in development).
