### ISSUE TITLE
Game crashes when launching with mod enabled

### ISSUE THREAD

**Issue by cobaltlol** [dimadencep/RemoveReloadingScreen#39]
### Minecraft version.

1.18.2

### Remove Reloading Screen version.

3.1.0

### What happened?

Game crashes upon launching with the mod enabled, it doesnt produce a crash report either so yeah

### Relevant logs

No crash report because it doesn't produce one in folders

**Comment by dima-dencep** [comment]
Provide a game log

**Comment by dima-dencep** [comment]
4.0.0, unless it causes additional problems, will be ported to 1.16.5, 1.18.2, 1.19.2, 1.20.1
I don't have time to fix old versions of this mod
