### ISSUE TITLE
Gone from Modrinth?

### ISSUE THREAD

**Issue by Madis0** [dimadencep/RemoveReloadingScreen#41]
### Minecraft version.

N/A

### Remove Reloading Screen version.

All

### What happened?

The mod seems to be removed from Modrinth? https://modrinth.com/mod/rrls/

### Relevant log.

N/A

**Comment by dimadencep** [comment]
I don't like their website :(

**Comment by Felix14-v2** [comment]
> I don't like their website :(

Seriously? But why?

**Comment by dimadencep** [comment]
strange
