### ISSUE TITLE
Latest version not on Modrinth

### ISSUE THREAD

**Issue by Madis0** [dimadencep/RemoveReloadingScreen#50]
### Minecraft version.

1.20.2

### Remove Reloading Screen version.

3.2.1

### What happened?

You did not upload latest version to Modrinth yet.

### Relevant log.

> Because 3.2.1 is beta 😀
> When I was ready to publish the version for 1.20.2, it said here that it wasn't available on modrinth, so I didn't publish it there

### Additional information.

Now 1.20.2 is an available option in Modrinth

**Comment by Zorklis** [comment]
This can be closed.
