### ISSUE TITLE
Sound doesn't play

### ISSUE THREAD

**Issue by Feliks-WR** [dimadencep/RemoveReloadingScreen#51]
### Minecraft version.

1.20.1

### Remove Reloading Screen version.

3.2.0-fabric

### What happened?

When I change mipmap levels, the screen appears.
Even after it disappears, the menu sounds don't play.

### Relevant log.

https://mclo.gs/GTxKS6b

### Additional information.

In the log

**Comment by dima-dencep** [comment]
The problem is not with rrls
