### ISSUE TITLE
Animation slider option for splash screen

### ISSUE THREAD

**Issue by Madis0** [dimadencep/RemoveReloadingScreen#52]
As we discussed in https://discord.com/channels/859124104644788234/1157594011251523604/1157594011251523604, what do you think of adding an option to configure vanilla splash animation speed to RRLS?

The configuration option could be defined in seconds from 0.00 to 2.00 (default).

**Comment by dima-dencep** [comment]
Rrls won't touch TitleScreen, only SplashOverlay, and only when it's [attached](https://github.com/dima-dencep/rrls/blob/1.20.x/dev/common/src/main/java/com/github/dimadencep/mods/rrls/mixins/SplashOverlayMixin.java#L69-L75)

**Comment by Madis0** [comment]
I think you're talking about this current option though? 
![image](https://github.com/dima-dencep/rrls/assets/8611110/d3adefc9-934b-4574-9586-059eeb51728c)
I'm suggesting a new option, as it seems relevant to the mod.

**Comment by dima-dencep** [comment]
> I think you're talking about this current option though?

The next release will change the system by which rrls will hide splash
This change is already on github, however I'm waiting for arch-loom to add neoforge support to release it
