### ISSUE TITLE
1.5.1 for 1.19.4?

### ISSUE THREAD

**Issue by Madis0** [dimadencep/RemoveReloadingScreen#6]
Is there a reason 1.5.0 is released for 1.16.5 but not 1.19.4 on Fabric?

**Comment by dima-dencep** [comment]
https://semver.org/spec/v2.0.0.html

**Comment by Madis0** [comment]
So... it is just a direct backport from a different version, with no unique changes?

**Comment by dima-dencep** [comment]
1.5.0 was released for all versions, in 1.5.1 was fixed bug (#5) which works only for 1.16.5
