### ISSUE TITLE
Refmap file for RRLS is not found by fabric

### ISSUE THREAD

**Issue by Kichura** [dimadencep/RemoveReloadingScreen#72]
### Minecraft version.

1.20.4

### Remove Reloading Screen version.

4.0.1

### What happened?

When starting up a 1.20.4 client using this mod, Fabric complains about RRLS's fabric refmap file not being found.

### Relevant log.

Client logs can be found [here](https://pastebin.com/raw/uXfmtuTx).

### Additional information.

Despite this warning being present, the mod functions normally during gameplay.

**Comment by dima-dencep** [comment]
It turns out that refmap is not generated in any way for an empty config, and I don't want to remove it
