### ISSUE TITLE
Rendering of the loading bar behind chat

### ISSUE THREAD

**Issue by BioTechproject27** [dimadencep/RemoveReloadingScreen#73]
### Minecraft version.

1.20.1

### Remove Reloading Screen version.

3.2.0-1.20.1-fabric

### What happened?

Rendering of Loading Bar infront of the chat, unless chat is opened, which makes it look cut off

It should render infront.

### Relevant log.

/

**Comment by dima-dencep** [comment]
This is normal behavior, the progress bar should not override the chat gui when you are in the game

**Comment by dima-dencep** [comment]
If I'm not mistaken, this has been lost in the newer versions

**Comment by dima-dencep** [comment]
It may be worth adding an option to the config

**Comment by BioTechproject27** [comment]
Ah I see. Yeah an option would be nice.
It just makes the bar look cut-off.

Also any newer versions are only for 1.20.4, could there be a backport? (to maybe at least 1.20+)

**Comment by dima-dencep** [comment]
> could there be a backport

I'm too lazy to do backports

**Comment by dima-dencep** [comment]
I plan to make the hiding system perfect, and then maybe,....
