### ISSUE TITLE
Early sending of status causes some servers to load their packs twice

### ISSUE THREAD

**Issue by Madis0** [dimadencep/RemoveReloadingScreen#74]
### Minecraft version.

1.20.2/1.20.4

### Remove Reloading Screen version.

3.2.4/3.3.0

### What happened?

On some servers, RRLS causes the first load of a server resource pack to fail, then it prevents the game from unloading the packs and loads the packs successfully on second try. May be related to resource packs with core shaders...
`play.mccisland.net` can be used to test this.

### Relevant log.

https://discord.com/channels/859124104644788234/1207673846707130368/1207677807849775184

### Additional information.

https://discord.com/channels/859124104644788234/1207673846707130368/1207704062427013171
You are already aware of this and suggested a workaround, but I reposted it here because it is still a bug and RRLS enables this option by default (so there may be more unaware users).

**Comment by dima-dencep** [comment]
There will be no fix for 1.20.2, for 1.20.4... we'll see...
