### ISSUE TITLE
Slow text coloring down

### ISSUE THREAD

**Issue by Madis0** [dimadencep/RemoveReloadingScreen#8]
The colorful text flickers too fast, which may harm people with sensitive eyes and cause epilepsy. Please slow the color switch down to half a second or so.

I know this option is opt-in, but people may not know how fast it flickers before they enable it, hence the suggestion. Or they may be harmed by the gif in the listing already...

**Comment by Madis0** [comment]
Apparently the option already exists

**Comment by dima-dencep** [comment]
The flicker rate can be seen on the Curseforge or Modrinth page in the gifs below

![Demonstration menu](https://i.imgur.com/Sm6vUmw.gif "menu")

**Comment by Madis0** [comment]
It does seem even faster in-game though.

**Comment by dima-dencep** [comment]
There is also a second example where it looks faster.

![Demonstration game](https://i.imgur.com/JLMxzwp.gif "game")

**Comment by dima-dencep** [comment]
@Madis0  If you need, I can add a tooltip to this option in the configuration, telling you that it flashes very quickly

**Comment by Madis0** [comment]
That could work, but don't you think it would be more pleasant to look at if it was slower?

**Comment by dima-dencep** [comment]
Yes, but it's not worth it.
