### ISSUE TITLE
[1.21 NeoForge] Jade and Remove Reloading Screen conflict

### ISSUE THREAD

**Issue by Starexify** [dimadencep/RemoveReloadingScreen#87]
### Minecraft version.

1.21

### Remove Reloading Screen version.

5.0.0

### What happened?

On 1.21 latest versions of the mods and neoforge. It doesn't show the overlay anymore. And the overlay renderer is crashed if trying to adjust it. (As seen in the crash report)

### Relevant logs

[crash-2024-07-01_12.31.15-client.txt](https://github.com/user-attachments/files/16051533/crash-2024-07-01_12.31.15-client.txt)

[latest.log](https://github.com/user-attachments/files/16051536/latest.log)

I don't know if needed but I still give this aswell may help?:
[JadeErrorOutput.txt](https://github.com/user-attachments/files/16051555/JadeErrorOutput.txt)

### Additional information

I tried only to load minecraft with Jade and Remove Reloading Screen together. I tested myself. Also reported to Jade's creator.

**Comment by dima-dencep** [comment]
This happens because jade tries to render its overlay on every screen.

On the title screen, when not everything is loaded yet, jade tries to get its theme, which causes a crash.

**Comment by dima-dencep** [comment]
Why doesn't this happen without rrls? I don't know, maybe because while loadingoverlay is on screen, it blocks the events that jade is listening for to render its overlay
