### ISSUE TITLE
Partial loading screen

### ISSUE THREAD

**Issue by Madis0** [dimadencep/RemoveReloadingScreen#9]
While testing the mod out with a lot of resource packs, I noticed that the game runs smoothly for a few seconds as it prepares to load and then it stutters for a second or two. 

What if you added an option to show the floating text in the smooth period and the Mojang loading screen only for those two seconds? I think that'd improve the UX a bit by making the stutter more obvious, as the user cannot do anything at that time anyway.

**Comment by dima-dencep** [comment]
As you wrote earlier "can harm people with sensitive eyes and cause epilepsy"

**Comment by Madis0** [comment]
Good point, it might happen for too short period in some computers.

**Comment by Felix14-v2** [comment]
@dimadencep maybe port or reimplement the Vanilla 1.15 reloading screen? In the past, the screen did not block your movement and at the same time maintained smoothness:

https://user-images.githubusercontent.com/75726196/228737101-d00bb410-c47b-499e-afd3-350e2f16c101.mp4
