### ISSUE TITLE
(Possible) Incompatibility with Continuity and something - Random textures on connected blocks

### ISSUE THREAD

**Issue by tajemniktv** [dimadencep/RemoveReloadingScreen#90]
### Minecraft version.

1.21

### Remove Reloading Screen version.

5.0.1 (Fabric)

### What happened?

![image](https://github.com/dima-dencep/rrls/assets/12156943/2fcb3a89-48c9-4714-892d-8496b3a4cd2a)

PepperCode tested with only Continuity, RRLS and Fabric API and the issue was not happening, which could indicate some triple mod incompatibility? List of my mods is available in logs and the first person's mod list to have this issue is available on Coyntinuity GH issue tracker. Might be worth starting with some basic mods like Sodium, Iris and then going to performance improving mods, maybe one of them is messing things up? On my end I removed ModernFix which didn't change a thing

### Relevant log.

Not really relevant but has more info on enabled mods, java, specs etc.:
https://mclo.gs/pxvPZkR

### Additional information.

Issue on Continuity GH tracker already open: https://github.com/PepperCode1/Continuity/issues/446

**Comment by dima-dencep** [comment]
I can't reproduce

**Comment by dima-dencep** [comment]
For reference, I tested on fabulously optimized with some additional mods and initial loading overlay hiding enabled

**Comment by iTitus** [comment]
I have the same problem on Fabulously Optimized 6.0.0-beta4 Fabric (most recent version as of now) for MC 1.21.

With a shader (Complementary 5.2.2) enabled and activated connected textures, all glass blocks and bookshelves have render errors.

Disabling connected textures or the shader or "Remove Reloading Screen" fixes it.


Might be related to:
- https://github.com/IrisShaders/Iris/issues/2369
- https://github.com/PepperCode1/Continuity/issues/437
- https://github.com/PepperCode1/Continuity/issues/446
