### ISSUE TITLE
RRLS v5.0.1 no longer completes initialization on NeoForge build v21.0.82-beta and later

### ISSUE THREAD

**Issue by Jerzerak** [dimadencep/RemoveReloadingScreen#93]
### Minecraft version.

1.21

### Remove Reloading Screen version.

5.0.1

### What happened?

Tried loading only RRLS on NeoForge using the default Minecraft launcher JRE and flags via PrismLauncher; all NeoForge builds v21.0.82-beta and later (latest is v21.0.95-beta as of writing) crash on the initialization phase. Per the NeoForge changelog the breaking change in v21.0.82-beta stems from an FML update that changed the config system rather significantly in [PR#172](https://github.com/neoforged/FancyModLoader/pull/172) and was pulled into mainline NeoForge in [PR#1239](https://github.com/neoforged/NeoForge/pull/1239).

### Relevant logs

[crash-2024-07-16_02.06.59-client.txt](https://mclo.gs/2mDyRHy)

**Comment by dima-dencep** [comment]
Yeah, I know
