### ISSUE TITLE
Crash with Alloy Forgery

### ISSUE THREAD

**Issue by ZannCoelz** [dimadencep/RemoveReloadingScreen#97]
### Minecraft version.

1.21

### Remove Reloading Screen version.

5.0.3

### What happened?

I am making a modpack and when I have both rrls and Alloy Forgery enabled my game crashes each time I try to enter the singleplayer world creation screen. This doesn't happen when I disable one of these mods.

### Relevant logs

Here are some crashreports I got from the same crash. I tried recreating the crash 3 times and got a slightly different report each time.
https://gist.github.com/ZannCoelz/ccfc46183e957be96418c23d2002f796

Here's one log from the crash:
https://gist.github.com/ZannCoelz/ba99b4fcc1f7befd7e68288fea0590e4

### Additional information

Here's a list of the mods I have. The same list should be in the crashreports.
https://gist.github.com/ZannCoelz/2e464d39316022473bc43535609b193e

I also reported this issue to Alloy Forgery, but after looking into it they recommended I report this here.

**Comment by dima-dencep** [comment]
Find a single line that says it's rrls

**Comment by dima-dencep** [comment]
Oh, I see.
